#1. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [2]:
import numpy as np

In [7]:
def function1():
    arr = np.array([1,7,13,105])
    print(arr)
    print(f"Size = {arr.size}")
    print(f"NBYTES = {arr.nbytes}")

In [8]:
function1()


[  1   7  13 105]
Size = 4
NBYTES = 32


#2.Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.


In [27]:
def function2(a):
    n1 = np.array([10,20,30,44,55])
    n2 = np.array([11,22,33,40,55])
    if n1[a]>n2[a]:
        print("n1 is greater")
    elif n1[a]<n2[a]:
        print("n2 is greater")
    else:
        print("Both are equal")
        

In [29]:
function2(3)

n1 is greater


#3.Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.


In [30]:
import numpy as np

In [32]:
arr1 = np.zeros(10)
print(arr1)

arr2=np.ones(10)
print(arr2)

arr3=np.ones(10)*5
print(arr3)

arr4=np.ones(10)*10
print(arr4)

arr5=np.ones(10)*20
print(arr5)

arr6=np.ones(10)*50
print(arr6)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


#4.Write a NumPy program to create an array of integers from 30 to 70.

In [34]:
arr1 = np.arange(30,71)
print(arr1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


#5.Write a NumPy program to create an array of integers from 50 to 95.

In [35]:
arr1 = np.arange(50,96)
print(arr1)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


#6. Write a NumPy program to create an array of all even integers from 20 to 80.

In [36]:
arr1 = np.arange(20,80,2)
print(arr1)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


#7. Write a NumPy program to create an array of all odd integers from 20 to 80.

In [42]:
arr1 = np.arange(21,80,2)
print(arr1)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


#8. Write a NumPy program to generate an array of 15 random numbers from 10 to 40.

In [44]:
n4 = np.random.randint(10,40,15)
print(n4)

[14 15 29 16 13 37 15 26 18 29 32 17 20 36 33]


#9. Write a NumPy program to generate an array of 10 random numbers from 30    to 50.

In [45]:
n4 = np.random.randint(30,50,10)
print(n4)

[31 33 37 46 49 49 42 41 36 46]


#10.Write a NumPy program to generate an array of 20 random numbers from 50    to 90.

In [46]:
n4 = np.random.randint(50,90,20)
print(n4)

[85 83 67 78 71 84 82 82 51 84 53 53 66 58 58 85 57 66 68 78]


#11.Create any two arrays & perform various mathematical operations.
    i.e. Addition, Substraction, Multiplication, Divide.

In [48]:
n1 = np.array([11,20,33,44])
n2 = np.array([10,20,30,40])
print(f"N1 = {n1}")
print(f"N2 = {n2}")
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)


N1 = [11 20 33 44]
N2 = [10 20 30 40]
[21 40 63 84]
[1 0 3 4]
[ 110  400  990 1760]
[1.1 1.  1.1 1.1]


#12. Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.

In [54]:
arr1 = np.arange(10,22)
arr1 = arr1.reshape([3,4])
print(arr1)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


#13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.


In [55]:
arr1 = np.eye(3)
print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 #14.Write a NumPy program to find the number of rows and columns in a given     matrix. 


In [3]:
import numpy as np
arr1 = np.arange(10,22)
arr1 = arr1.reshape([3,4])
print(arr1)
print("Rows and Columns are")
print(arr1.shape) 

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Rows and Columns are
(3, 4)


#Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.

In [4]:
x = np.diag([1, 2, 3, 4, 5])
print(x) 


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#16. Write a NumPy program to create a 3x3x3 array filled with arbitrary     values.


In [5]:
x = np.random.random((3, 3, 3))
print(x)

[[[0.85641329 0.39773291 0.38470259]
  [0.57778974 0.7690482  0.36186039]
  [0.47091735 0.40029834 0.9318606 ]]

 [[0.44050811 0.38351133 0.41510669]
  [0.26204643 0.37552939 0.38895085]
  [0.94958681 0.28838808 0.630228  ]]

 [[0.8519643  0.76886849 0.13302231]
  [0.99474022 0.04470626 0.57526829]
  [0.19381886 0.78444567 0.05353429]]]


#17. Write a NumPy program to create a 2x3x4 array filled with arbitrary     values.


In [6]:
x = np.random.random((2, 3, 4))
print(x)

[[[0.7489508  0.06683889 0.63335711 0.85528731]
  [0.91714214 0.30250626 0.20475011 0.95139766]
  [0.39262729 0.99613333 0.4861771  0.0132481 ]]

 [[0.63936125 0.58005746 0.95517574 0.97127458]
  [0.11118598 0.26684658 0.68185626 0.09137923]
  [0.3299199  0.64037122 0.97792105 0.45971118]]]


#18. Write a NumPy program to convert a list of numeric values into a one-    dimensional NumPy array.


In [11]:
l = [12.23, 13.32, 100,36.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)


Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


#19. Write a NumPy program to create a 3x3 matrix with values ranging from 2     to 10.


In [12]:
x = np.arange(2, 11).reshape(3, 3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


#20. Write a NumPy program to create an array with values ranging from 12 to 38.


In [13]:
x = np.arange(12, 39)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


#21. Write a NumPy program to reverse an array (the first element becomes the last).


In [14]:
x = np.arange(1, 20)

print("Original array:")
print(x)

print("Reverse array:")
x = x[::-1]
print(x) 

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reverse array:
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


#22. Write a NumPy program to convert an data type into to a floating type.


In [15]:
a = [1, 2, 3, 4]
print("Original array")
print(a)

# Converting the array 'a' to a NumPy array of type float using asfarray()
x = np.asfarray(a)
print("Array converted to a float type:")
print(x) 

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


#23. Write a NumPy program to convert a list array.


In [17]:
lst = [1, 7, 0, 6, 2, 5, 6]
 
# converting list to array
arr = np.array(lst)
 
# displaying list
print ("List: ", lst)
 
# displaying array
print ("Array: ", arr)

List:  [1, 7, 0, 6, 2, 5, 6]
Array:  [1 7 0 6 2 5 6]


#24. Write a NumPy program to get the element-wise remainder of an array of division.


In [18]:
x = np.arange(7)

# Displaying the original array
print("Original array:")
print(x)

# Computing the element-wise remainder of division by 5 and displaying the result
print("Element-wise remainder of division:")
print(np.remainder(x, 2)) 

Original array:
[0 1 2 3 4 5 6]
Element-wise remainder of division:
[0 1 0 1 0 1 0]


#25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.


In [19]:
x = np.arange(20,51)

# Displaying the original array
print("Original array:")
print(x)

# Computing the element-wise remainder of division by 5 and displaying the result
print("Element-wise remainder of division:")
print(np.remainder(x, 3)) 

Original array:
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50]
Element-wise remainder of division:
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
